x-vault-common: &vault-common
  image: hashicorp/vault:1.20.1
  restart: unless-stopped
  cap_add:
    - IPC_LOCK
  user: root
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  healthcheck:
    test:
      - "CMD"
      - "curl"
      - "-fs"
      - "http://127.0.0.1:8200/v1/sys/health"
    interval: 10s
    timeout: 5s
    retries: 3

services:
  vault:
    volumes:
      - vault-data:/vault/data
    configs:
      - source: vault-cfg
        target: /etc/vault/vault.hcl
    ports:
      - "8200:8200"
    entrypoint: vault server -config=/etc/vault/vault.hcl
    <<: *vault-common

volumes:
  vault-data:
    driver: local

configs:
  vault-cfg:
    file: ./config/vault.hcl
