x-elasticsearch-common: &elasticsearch-common
  image: docker.io/elasticsearch:9.1.2
  restart: unless-stopped
  entrypoint: /usr/local/bin/docker-entrypoint.sh eswrapper
  ulimits:
    memlock:
      soft: -1
      hard: -1
  healthcheck:
    test:
      - "CMD-SHELL"
      - |
        curl -s -u elastic:$${ELASTIC_PASSWORD} http://127.0.0.1:9200/_cluster/health | grep -E '"status":"(green|yellow)"'
    interval: 10s
    timeout: 5s
    retries: 3

x-elasticsearch-environment: &elasticsearch-environment
  ELASTIC_PASSWORD: ""
  ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  bootstrap.memory_lock: "true"
  cluster.name: "elasticsearch-cluster"
  discovery.type: "single-node"
  network.host: "0.0.0.0"
  xpack.security.enabled: "false"

services:
  elasticsearch:
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      <<: *elasticsearch-environment
      node.name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    <<: *elasticsearch-common

volumes:
  elasticsearch-data:
    driver: local
