x-redis-common: &redis-common
  image: docker.io/redis:8.2.0
  restart: unless-stopped
  entrypoint: redis-server /usr/local/etc/redis/redis.conf
  healthcheck:
    test:
      - "CMD-SHELL"
      - |
        redis-cli -p $${REDIS_PORT} ping | grep PONG
    interval: 10s
    timeout: 5s
    retries: 3

services:
  redis-init:
    image: docker.io/redis:8.2.0
    depends_on:
      redis-node-1:
        condition: service_started
      redis-node-2:
        condition: service_started
      redis-node-3:
        condition: service_started
    entrypoint: redis-cli --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 --cluster-replicas 0 --cluster-yes
    restart: "no"

  redis-node-1:
    volumes:
      - redis-node-1-data:/data
    configs:
      - source: redis-node-1-cfg
        target: /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
      - "16379:16379"
    <<: *redis-common

  redis-node-2:
    volumes:
      - redis-node-2-data:/data
    configs:
      - source: redis-node-2-cfg
        target: /usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
      - "16380:16379"
    <<: *redis-common

  redis-node-3:
    volumes:
      - redis-node-3-data:/data
    configs:
      - source: redis-node-3-cfg
        target: /usr/local/etc/redis/redis.conf
    ports:
      - "6382:6379"
      - "16382:16379"
    <<: *redis-common

volumes:
  redis-node-1-data:
    driver: local
  redis-node-2-data:
    driver: local
  redis-node-3-data:
    driver: local

configs:
  redis-node-1-cfg:
    file: ./config/redis-node-1.conf
  redis-node-2-cfg:
    file: ./config/redis-node-2.conf
  redis-node-3-cfg:
    file: ./config/redis-node-3.conf
